# Generated by Django 5.0.4 on 2026-05-08 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIEMAlertLog',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('threat_score', models.FloatField()),
                ('action_taken', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'siem_alert_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
